# coding: utf-8

"""
    Classify

    Classify Custom Image Recognition Service  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: info@inoven.ai
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_new_model(self):
        """Test case for create_new_model

        Create New Model  # noqa: E501
        """
        pass

    def test_delete_model(self):
        """Test case for delete_model

        Delete Model  # noqa: E501
        """
        pass

    def test_get_models_list(self):
        """Test case for get_models_list

        Get Models List  # noqa: E501
        """
        pass

    def test_tag_image_by_url(self):
        """Test case for tag_image_by_url

        Tag Image by Using Image Url  # noqa: E501
        """
        pass

    def test_tag_local_image(self):
        """Test case for tag_local_image

        Predict by Image  # noqa: E501
        """
        pass

    def test_update_model(self):
        """Test case for update_model

        Update Model  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
