# coding: utf-8

# flake8: noqa
"""
    Classify

    Classify Custom Image Recognition Service  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: info@inoven.ai
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.inline_object import InlineObject
